server:
  port: 8081

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  server:
    port: 3388

logging:
  file: logs/${spring.application.name}-log
  level:
    com.xmutca: info


spring:
  boot:
    admin:
      client:
        url: http://localhost:8686



system:
  jwt:
    access_token_expire_timeout: 3600
    refresh_token_expire_timeout: 2592000


feign:
  hystrix:
    enabled: true